SELECT
    ts.descripcion||'.'||s.descripcion AS SISTEMA_SALUD,
    COUNT(*) AS TOTAL_ATENCIONES
FROM ATENCION a
    JOIN PACIENTE p ON a.pac_run = p.pac_run
    JOIN SALUD s ON p.sal_id = s.sal_id
    JOIN TIPO_SALUD ts ON s.tipo_sal_id = ts.tipo_sal_id
WHERE EXTRACT(YEAR FROM a.fecha_atencion) = EXTRACT(YEAR FROM SYSDATE)
    AND EXTRACT(MONTH FROM a.fecha_atencion) = 9
GROUP BY ts.descripcion, s.descripcion
HAVING COUNT(*) > (SELECT AVG(COUNT(*))
    FROM ATENCION a
    JOIN PACIENTE p ON a.pac_run = p.pac_run
    JOIN SALUD s ON p.sal_id = s.sal_id
    JOIN TIPO_SALUD ts ON s.tipo_sal_id = ts.tipo_sal_id
WHERE EXTRACT(YEAR FROM a.fecha_atencion) = EXTRACT(YEAR FROM SYSDATE)
    AND EXTRACT(MONTH FROM a.fecha_atencion) = 9
GROUP BY ts.descripcion, s.descripcion)
;
--CASO 2

--SELECT * from paciente
select * from porc_descto_3ra_edad

SELECT 
    TO_CHAR(PAC_RUN,'99G999G999') ||'-'||DV_RUN AS "RUT PACIENTE",
    PNOMBRE||' '||SNOMBRE||' '||APATERNO||' '||AMATERNO AS "NOMBRE PACIENTE",
    ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) AS "AÑOS",
    CASE WHEN ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) BETWEEN 65 AND 70 THEN ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12)*0.02
    WHEN ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) BETWEEN 71 AND 75 THEN ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12)*0.05
    WHEN ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) BETWEEN 76 AND 80 THEN ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12)*0.08
    WHEN ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) BETWEEN 81 AND 85 THEN ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12)*0.10
    WHEN ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) > 120 THEN SUM()*0.20
END "PORCENTAJE DESCUENTO"
FROM PACIENTE OO    
    JOIN PORC_DESCTO_3RA_EDAD O ON O.PORCENTAJE_DESCTO = OO.PORCENTAJE_DESCTO
    WHERE EXTRACT(YEAR FROM FECHA_NACIMIENTO)= 2020
    GROUP BY TO_CHAR(



