--SELECT * FROM empleado;
--CASO 1
SELECT
    TO_CHAR(numrun_emp,'99G999G999')||'-'||DVRUN_EMP as "run empleado",
    PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||SUBSTR(APPATERNO_EMP,0,1)||'.'||APMATERNO_EMP as "nombre empleado",
    Direccion_emp AS "DIRECCIÓN",
    NVL(TO_CHAR(FONO_FIJO_EMP),'no posee telefono') as "telefono",
    NVL(TO_CHAR(CELULAR_EMP),'no posee celular') as "celular",
    id_comuna as "comuna"
FROM empleado
ORDER BY &order_column
;

--CASO 2
SELECT
'EL EMPLEADO'||' '||PNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP||' '||'estuvo de cumpleaños el'||' '||TO_CHAR(FECHA_NAC,'DD "DE" MONTH.')||'Cumplió'||' '||ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NAC)/12)||' '||'AÑOS' as "fecha de nacimiento"
FROM empleado
WHERE EXTRACT(MONTH FROM FECHA_NAC)=7
ORDER BY EXTRACT(DAY FROM FECHA_NAC),APPATERNO_EMP ASC
;

--CASO 3
--SELECT * FROM CAMION
SELECT 
    T.NOMBRE_TIPO_CAMION AS "TIPO CAMION",
    C.NRO_PATENTE AS "NRO PATENTE",
    C.ANIO AS "AÑO",
    TO_CHAR(C.VALOR_ARRIENDO_DIA,'$99G999') AS "VALOR ARRIENDO DIA",
    NVL(TO_CHAR(C.VALOR_GARANTIA_DIA,'$999G999'),0) AS "VALOR GARANTIA DIA",
    NVL(TO_CHAR(C.VALOR_ARRIENDO_DIA+C.VALOR_GARANTIA_DIA,'$999G999'),0) AS "VALOR TOTAL DIA"
FROM CAMION C
JOIN TIPO_CAMION T ON C.ID_TIPO_CAMION = T.ID_TIPO_CAMION
ORDER BY T.NOMBRE_TIPO_CAMION,C.VALOR_ARRIENDO_DIA DESC, C.VALOR_GARANTIA_DIA ASC;

--CASO 4
--SELECT * FROM EMPLEADO
SELECT 
    TO_CHAR(sysdate,'MM/yyyy') AS FECHA,
    TO_CHAR(NUMRUN_EMP,'99G999G999') ||'-'||DVRUN_EMP AS "RUN EMPLEADO" ,
    PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP,
    TO_CHAR(SUELDO_BASE,'$99G999G999') AS "SUELDO BASE",
    CASE WHEN SUELDO_BASE>320000 AND SUELDO_BASE<450000 THEN TO_CHAR((20000000*0.05),'$99G999G999')
        WHEN SUELDO_BASE>450001 AND SUELDO_BASE<600000 THEN TO_CHAR((20000000*0.035),'$99G999G999')
        WHEN SUELDO_BASE>600001 AND SUELDO_BASE<900000 THEN TO_CHAR((20000000*0.025),'$99G999G999')
        WHEN SUELDO_BASE>900001 AND SUELDO_BASE<1800000 THEN TO_CHAR((20000000*0.015),'$99G999G999')
        WHEN SUELDO_BASE>1800001 THEN TO_CHAR((20000000*0.01),'$99G999G999')
        END "BONIFICACION"
FROM EMPLEADO
ORDER BY APPATERNO_EMP;
--CASO 5
SELECT 
    NUMRUN_EMP ||'-'||DVRUN_EMP AS "RUN EMPLEADO",
    PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
    TRUNC((SYSDATE-FECHA_CONTRATO)/365) AS "AÑOS DE SERVICIO",
    TO_CHAR(SUELDO_BASE,'$99G999G999') AS "SUELDO BASE",
    CASE WHEN SUELDO_BASE>=450000 THEN TO_CHAR((SUELDO_BASE*(TRUNC((SYSDATE-FECHA_CONTRATO)/365)/100)),'$99G999G999')
        WHEN SUELDO_BASE<450000 THEN TO_CHAR((SUELDO_BASE*(TRUNC((SYSDATE-FECHA_CONTRATO)/365)/100)),'$99G999G999')   
    END "VALOR MOVILIZACION",
    CASE WHEN SUELDO_BASE>=450000 THEN TO_CHAR((SUELDO_BASE*(SUBSTR(SUELDO_BASE,0,1)/100)),'$99G999G999')
        WHEN SUELDO_BASE<450000 THEN TO_CHAR((SUELDO_BASE*(SUBSTR(SUELDO_BASE,0,2)/100)),'$99G999G999')
    END "BONIFICACION",
    CASE WHEN SUELDO_BASE>=450000 THEN TO_CHAR((SUELDO_BASE*(SUBSTR(SUELDO_BASE,0,1)/100))+(SUELDO_BASE*(TRUNC((SYSDATE-FECHA_CONTRATO)/365)/100)),'$99G999G999')
        WHEN SUELDO_BASE<450000 THEN TO_CHAR((SUELDO_BASE*(SUBSTR(SUELDO_BASE,0,2)/100))+(SUELDO_BASE*(TRUNC((SYSDATE-FECHA_CONTRATO)/365)/100)),'$99G999G999')
    END "TOTAL" 
FROM EMPLEADO
WHERE ID_COMUNA IN (117,118,120,122,126);
--CASO 6
SELECT 
    EXTRACT(YEAR FROM SYSDATE) AS "AÑO TRIBUTARIO",
    TO_CHAR(NUMRUN_EMP,'99G999G999') ||'-'||DVRUN_EMP AS "RUN EMPLEADO",
    PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
    TRUNC((SYSDATE-TO_DATE('01/01/22'))/31) AS "MESES TRABAJADOS",
    TRUNC((SYSDATE-FECHA_CONTRATO)/365) AS "AÑOS DE SERVICIO",
    SUELDO_BASE AS "SUELDO BASE MENSUAL",
    SUELDO_BASE*12 AS "SUELDO BASE ANUAL",
    TRUNC(SUELDO_BASE*(TRUNC((SYSDATE-FECHA_CONTRATO)/365)/100))*12 AS "BONO POR AÑOS ANUAL",
    TRUNC(SUELDO_BASE*0.12)*12 AS "MOVILIZACION ANUAL",
    TRUNC(SUELDO_BASE*0.20)*12 AS "COLACION ANUAL",
    TRUNC(((SUELDO_BASE*0.20)+(SUELDO_BASE*0.12)+SUELDO_BASE+(SUELDO_BASE*(TRUNC((SYSDATE-FECHA_CONTRATO)/365)/100)))*12) AS "SUELDO BRUTO ANUAL",
    TRUNC((SUELDO_BASE+SUELDO_BASE*(TRUNC((SYSDATE-FECHA_CONTRATO)/365)/100))*12) AS "RENTA IMPONIBLE ANUAL"
FROM EMPLEADO
ORDER BY NUMRUN_EMP;