--CASO 1
SELECT 
    TO_CHAR(C.NUMRUN,'09G999G999')||'-'||C.DVRUN AS "RUN CLIENTE",
    INITCAP(C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO) AS "NOMBRE CLIENTE",
    TO_CHAR(FECHA_NACIMIENTO,'DD "De" Month') AS "FECHA DE NACIMIENTO",
    SR.DIRECCION||'/'||UPPER(R.NOMBRE_REGION) AS "DIRECCION"
FROM CLIENTE C
    JOIN SUCURSAL_RETAIL SR ON SR.COD_REGION = C.COD_REGION
                        AND SR.COD_PROVINCIA = C.COD_PROVINCIA
                        AND SR.COD_COMUNA = C.COD_COMUNA
    JOIN REGION R ON R.COD_REGION = SR.COD_REGION
    WHERE EXTRACT(MONTH FROM FECHA_NACIMIENTO) = 9
--WHERE EXTRACT(MONTH FROM FECHA_NACIMIENTO) = EXTRACT(MONTH FROM SYSDATE)+1
    AND C.COD_REGION = 13
    ORDER BY "FECHA DE NACIMIENTO" ASC, APPATERNO;

--CASO 2
SELECT 
    TO_CHAR(C.NUMRUN,'09G999G999')||'-'||C.DVRUN AS "RUT CLIENTE",
    C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(SUM(TTC.MONTO_TRANSACCION),'$99G999G999') AS "MONTO COMPRAS",
    TO_CHAR((SUM(TTC.MONTO_TRANSACCION)/10000)*250,'$99G999G999') AS "PUNTOS"
FROM CLIENTE C
    INNER JOIN TARJETA_CLIENTE TC ON TC.NUMRUN = C.NUMRUN
    INNER JOIN TRANSACCION_TARJETA_CLIENTE TTC ON TTC.NRO_TARJETA = TC.NRO_TARJETA
    WHERE EXTRACT(YEAR FROM TTC.FECHA_TRANSACCION) = 2021
    GROUP BY C.NUMRUN,C.DVRUN,C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO
    ORDER BY "MONTO COMPRAS"
;

--CASO 3
	
SELECT 
    TO_CHAR(TTC.FECHA_TRANSACCION,'MMYYYY') AS "FECHA TRANSACCION",
    TTT.NOMBRE_TPTRAN_TARJETA AS "TIPO DE TRANSACCION",
    TO_CHAR(SUM(TTC.MONTO_TOTAL_TRANSACCION),'$99G999G999') AS "MONTO AVANCE/S. AVANCE",
    TO_CHAR(SUM(TTC.MONTO_TOTAL_TRANSACCION * (ASB.PORC_APORTE_SBIF/100)),'$99G990G999') AS "APORTE A LA SBIF"
FROM TRANSACCION_TARJETA_CLIENTE TTC
    JOIN TIPO_TRANSACCION_TARJETA TTT ON TTT.COD_TPTRAN_TARJETA = TTT.COD_TPTRAN_TARJETA
    JOIN APORTE_SBIF ASB ON TTC.MONTO_TOTAL_TRANSACCION BETWEEN ASB.MONTO_INF_AV_SAV AND ASB.MONTO_SUP_AV_SAV
    WHERE TTT.NOMBRE_TPTRAN_TARJETA IN ('Avance en Efectivo', 'Súper Avance en Efectivo')
    AND EXTRACT(YEAR FROM TTC.FECHA_TRANSACCION) = EXTRACT(YEAR FROM SYSDATE)
    GROUP BY TO_CHAR(TTC.FECHA_TRANSACCION,'MMYYYY'),TTT.NOMBRE_TPTRAN_TARJETA
    ORDER BY "FECHA TRANSACCION","TIPO DE TRANSACCION";
--CASO 4  
SELECT 
TO_CHAR(C.NUMRUN,'99G999G999')||'-'||C.DVRUN AS "RUN CLIENTE",
C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO AS "NOMBRE CLIENTE",
RTRIM(TO_CHAR(NVL(SUM(TTC.MONTO_TOTAL_TRANSACCION),0),'$999G999G999'))AS "COMPRAS/AVANCES/S.AVANCES",
    CASE WHEN NVL(SUM(TTC.MONTO_TOTAL_TRANSACCION),0) BETWEEN 0 AND 100000 THEN 'SIN CATEGORIZACION'
    WHEN NVL(SUM(TTC.MONTO_TOTAL_TRANSACCION),0) BETWEEN 100000  AND  1000000 THEN 'BRONC'
    WHEN NVL(SUM(TTC.MONTO_TOTAL_TRANSACCION),0) BETWEEN 1000001 AND 4000000 THEN 'PLATA'
    WHEN NVL(SUM(TTC.MONTO_TOTAL_TRANSACCION),0) BETWEEN 4000001 AND 8000000 THEN 'SILVER'
    WHEN NVL(SUM(TTC.MONTO_TOTAL_TRANSACCION),0) BETWEEN 8000001 AND 15000000 THEN 'GOLD'
    WHEN NVL(SUM(TTC.MONTO_TOTAL_TRANSACCION),0)>15000000 THEN 'PLATINUM'
    END AS "CATEGORIZACION DEL CLIENTE"
FROM CLIENTE C
INNER JOIN TARJETA_CLIENTE TC ON TC.NUMRUN = C.NUMRUN
LEFT JOIN TRANSACCION_TARJETA_CLIENTE TTC ON TTC.NRO_TARJETA = TC.NRO_TARJETA
GROUP BY TO_CHAR(C.NUMRUN,'09G999G999')||'-'||DVRUN,PNOMBRE,SNOMBRE,APPATERNO,APMATERNO
ORDER BY APPATERNO,"COMPRAS/AVANCES/S.AVANCES" DESC