--CASO 1
--SELECT*FROM CLIENTE NATURAL JOIN PROFESION_OFICIO
SELECT
TO_CHAR(NUMRUN,'99G999G999') ||'-'||DVRUN AS "RUN CLIENTE",
INITCAP(PNOMBRE)||' '||INITCAP(SNOMBRE)||' '||INITCAP(APPATERNO)||' '||INITCAP(APMATERNO) AS "NOMBRE CLIENTE",
NOMBRE_PROF_OFIC AS "PROFESION/OFICIO",
TO_CHAR(FECHA_NACIMIENTO,'DD "de" Month') AS "DIA DE CUMPLEAÑOS"
FROM Cliente NATURAL JOIN PROFESION_OFICIO
WHERE EXTRACT(MONTH FROM FECHA_NACIMIENTO)=9
ORDER BY EXTRACT(DAY FROM FECHA_NACIMIENTO) ASC, APPATERNO ASC
--CASO 2
SELECT 
    TO_CHAR(C.NUMRUN,'09G999G999')||'-'||C.DVRUN AS "RUN CLIENTE",
    C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO AS "NOMBRE CLIENTE",
    TO_CHAR(SUM(CC.MONTO_SOLICITADO),'$99G999G999') AS "MONTO SOLICITADO",
    TO_CHAR((SUM(CC.MONTO_SOLICITADO)/100000)*1200,'$99G999G999') AS "TOTAL PESOS TODOSUMA"
FROM CLIENTE C
JOIN CREDITO_CLIENTE CC ON CC.NRO_CLIENTE = C.NRO_CLIENTE
    WHERE EXTRACT(YEAR FROM CC.FECHA_SOLIC_CRED) = EXTRACT(YEAR FROM SYSDATE)-1
    GROUP BY C.NUMRUN, C.DVRUN, C.PNOMBRE,C.SNOMBRE,C.APPATERNO,C.APMATERNO
    ORDER BY "TOTAL PESOS TODOSUMA" ASC, APPATERNO DESC;

--CASO 3
SELECT 
    TO_CHAR(CC.FECHA_SOLIC_CRED,'mmyyyy') AS "MES TRANSACCION",
    C.NOMBRE_CREDITO AS "TIPO CREDITO",
    SUM(MONTO_CREDITO) AS "MONTO SOLICITADO CREDITO",
CASE WHEN SUM(MONTO_CREDITO) BETWEEN 100000 AND 1000000 THEN SUM(MONTO_CREDITO)*0.01
    WHEN SUM(MONTO_CREDITO) BETWEEN 1000001 AND 2000000 THEN SUM(MONTO_CREDITO)*0.02
    WHEN SUM(MONTO_CREDITO) BETWEEN 2000001 AND 4000000 THEN SUM(MONTO_CREDITO)*0.03
    WHEN SUM(MONTO_CREDITO) BETWEEN 4000001 AND 6000000 THEN SUM(MONTO_CREDITO)*0.04
    WHEN SUM(MONTO_CREDITO) > 6000000 THEN SUM(MONTO_CREDITO)*0.07
END "APORTE A LA SBIF"
FROM CREDITO_CLIENTE CC
JOIN CREDITO C ON C.COD_CREDITO = CC.COD_CREDITO
    WHERE EXTRACT(YEAR FROM FECHA_SOLIC_CRED) = EXTRACT(YEAR FROM SYSDATE)-1
    GROUP BY TO_CHAR(CC.FECHA_SOLIC_CRED,'mmyyyy'),C.NOMBRE_CREDITO
    ORDER BY "MES TRANSACCION","TIPO CREDITO"

--CASO 4
SELECT TO_CHAR(NUMRUN,'09G999G999')||'-'||DVRUN AS "RUT CLIENTE",
PNOMBRE||' '||SNOMBRE||' '||APPATERNO||' '||APMATERNO AS "NOMBRE DEL CLIENTE",
TO_CHAR(SUM(PIC.MONTO_TOTAL_AHORRADO),'$99G999G999') AS "MONTO TOTAL AHORRADO",
CASE WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 100000 AND 1000000 THEN 'BRONCE'
WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 1000001 AND 4000000 THEN 'PLATA'
WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 4000001 AND 8000000 THEN 'SILVER'
WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 8000001 AND 15000000 THEN 'GOLD'
WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) > 15000000 THEN 'PLATINUM'
END "CATEGORIA CLIENTE"
FROM CLIENTE C
JOIN PRODUCTO_INVERSION_CLIENTE PIC ON PIC.NRO_CLIENTE = C.NRO_CLIENTE
GROUP BY NUMRUN,DVRUN,PNOMBRE,SNOMBRE,APPATERNO,APMATERNO
ORDER BY APPATERNO ASC, "MONTO TOTAL AHORRADO" DESC;

--CASO 5
SELECT EXTRACT(YEAR FROM SYSDATE) AS "AÑO TRIBUTARIO",
TO_CHAR(NUMRUN,'09G999G999')||'-'||DVRUN AS "RUT CLIENTE",
INITCAP(PNOMBRE)||' '||SUBSTR(SNOMBRE,0,1)||'. '||INITCAP(APPATERNO)||' '||INITCAP(APMATERNO) AS "NOMBRE DEL CLIENTE",
COUNT(PIC.NRO_CLIENTE) AS "TOTAL PROD. INV AFECTADOS IMPTO",
TO_CHAR(SUM(PIC.MONTO_TOTAL_AHORRADO),'$99G999G999') AS "MONTO TOTAL AHORRADO"
FROM CLIENTE C
JOIN PRODUCTO_INVERSION_CLIENTE PIC ON PIC.NRO_CLIENTE = C.NRO_CLIENTE
HAVING SUM(PIC.MONTO_TOTAL_AHORRADO) > 7833186 
GROUP BY EXTRACT(YEAR FROM SYSDATE), NUMRUN,DVRUN,PNOMBRE,SNOMBRE,APPATERNO,APMATERNO
ORDER BY APPATERNO;

--CASO 6 PARTE 1
SELECT TO_CHAR(NUMRUN,'09G999G999')||'-'||DVRUN AS "RUT CLIENTE",
INITCAP(PNOMBRE)||' '||INITCAP(SNOMBRE)||' '||INITCAP(APPATERNO)||' '||INITCAP(APMATERNO) AS "NOMBRE DEL CLIENTE",
COUNT(CC.NRO_CLIENTE) AS "TOTAL CREDITOS SOLICITADOS",
RTRIM(TO_CHAR(SUM(CC.MONTO_SOLICITADO),'$99G999G999')) AS "MONTO TOTAL CREDITOS"
FROM CLIENTE C
JOIN CREDITO_CLIENTE CC ON CC.NRO_CLIENTE = C.NRO_CLIENTE
WHERE EXTRACT(YEAR FROM FECHA_OTORGA_CRED) = EXTRACT(YEAR FROM SYSDATE)-1
GROUP BY NUMRUN, DVRUN, PNOMBRE,SNOMBRE,APPATERNO,APMATERNO
ORDER BY APPATERNO;

--CASO 6 PARTE 2
SELECT TO_CHAR(NUMRUN,'09G999G999')||'-'||DVRUN AS "RUT CLIENTE",
INITCAP(PNOMBRE)||' '||INITCAP(SNOMBRE)||' '||INITCAP(APPATERNO)||' '||INITCAP(APMATERNO) AS "NOMBRE DEL CLIENTE",
COALESCE(TO_CHAR(MAX(CASE WHEN m.cod_tipo_mov = 1 THEN m.monto_movimiento 
                            ELSE null END), 'L99g999g999'), 'No realizó') as "ABONO",
COALESCE(TO_CHAR(MAX(CASE WHEN m.cod_tipo_mov = 2 THEN m.monto_movimiento 
                            ELSE null END), 'L99g999g999'), 'No realizó') as "RESCATES"
FROM CLIENTE C
JOIN MOVIMIENTO M ON M.NRO_CLIENTE = C.NRO_CLIENTE
WHERE EXTRACT(YEAR FROM M.FECHA_MOVIMIENTO) = EXTRACT(YEAR FROM SYSDATE)
GROUP BY TO_CHAR(NUMRUN,'09G999G999')||'-'||DVRUN, PNOMBRE,SNOMBRE,APPATERNO,APMATERNO
ORDER BY APPATERNO;
