--SELECT * FROM PROPIEDAD_ARRENDADA
--CASO 1
SELECT 
    FECINI_ARRIENDO
FROM PROPIEDAD_ARRENDADA
WHERE EXTRACT(YEAR FROM FECINI_ARRIENDO)=&YEAR;

--CASO 2
SELECT 
    NUMRUT_CLI||'-'||DVRUT_CLI AS "RUT CLIENTE",
    NOMBRE_CLI||' '||APPATERNO_CLI||' '||APMATERNO_CLI AS "NOMBRE CLIENTE",
    RENTA_CLI AS "RENTA",
    FONOFIJO_CLI AS "TELEFONO FIJO",
    CELULAR_CLI AS "CELULAR"
FROM CLIENTE
WHERE RENTA_CLI>=800000
AND ID_ESTCIVIL IN (1,3,4)
ORDER BY APPATERNO_CLI, NOMBRE_CLI;

--CASO 3
--PARTE 1
SELECT 
    NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE DE EMPLEADO",
    SUELDO_EMP,
    SUELDO_EMP*1.085 AS "SUELDO REAJUSTADO",
    (SUELDO_EMP*1.085)-SUELDO_EMP AS "AUMENTO"
FROM EMPLEADO
ORDER BY AUMENTO DESC;
--PARTE 2
SELECT 
    NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE DE EMPLEADO",
    SUELDO_EMP,
    SUELDO_EMP*1.20 AS "SUELDO REAJUSTADO",
    (SUELDO_EMP*1.20)-SUELDO_EMP AS "AUMENTO"
FROM EMPLEADO
WHERE SUELDO_EMP >= 200000 AND SUELDO_EMP<=400000
ORDER BY AUMENTO DESC;

--CASO 4
SELECT 
    NUMRUT_EMP||'-'||DVRUT_EMP AS "RUT EMPLEADO",
    NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE DE EMPLEADO",
    SUELDO_EMP AS "SALARIO ACTUAL",
    SUELDO_EMP*(&AUMENTO /100) AS "SUELDO REAJUSTADO"
FROM EMPLEADO
WHERE SUELDO_EMP<=500000
AND ID_CATEGORIA_EMP <> 3
ORDER BY APPATERNO_EMP;
--CASO 5
--PRUEBA 1
SELECT 
    NRO_PROPIEDAD AS "NUMERO PROPIEDAD", 
    FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION",
    SUPERFICIE AS "SUPERFICIE",
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD) = EXTRACT(YEAR FROM SYSDATE)
ORDER BY FECHA_ENTREGA_PROPIEDAD;

--PRUEBA 2
SELECT 
    NRO_PROPIEDAD AS "NUMERO PROPIEDAD", 
    FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION",
    SUPERFICIE AS "SUPERFICIE",
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD) = 2010
AND EXTRACT(MONTH FROM FECHA_ENTREGA_PROPIEDAD) = 2
ORDER BY FECHA_ENTREGA_PROPIEDAD;

--TABLA CREADA
CREATE TABLE DET_PROPIEDADES_ARRIENDO_VENTA
 AS SELECT 
    NRO_PROPIEDAD AS "NUMERO PROPIEDAD", 
    FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD",
    DIRECCION_PROPIEDAD AS "DIRECCION",
    SUPERFICIE AS "SUPERFICIE",
    NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS",
    NRO_BANOS AS "CANTIDAD DE BAÑOS",
    VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD) = EXTRACT(YEAR FROM SYSDATE)
ORDER BY FECHA_ENTREGA_PROPIEDAD;

SELECT *
FROM det_propiedades_arriendo_venta


